### ISSUE TITLE
Input stuck

### ISSUE THREAD

**Issue by samsonchan666** [samsonchan666/Line-chatbot-for-COMP3111-GP29#23]
type in "mon"
choose 2D001
choose 11/6/2017
choose yes <- chatbot get stuck here
no problem if choosing no and select 18/11/2017

**Comment by harrysky1997** [comment]
run input handler again because it is actually 6/11/2017 and i change booking.csv
there are still some incorrect Date corresponding to the weekday and i will change .csv correctly later
